#!/usr/bin/env python3
"""
Create GitHub issues from brutal code review findings.
No mercy - creates issues for everything that's wrong.
"""

import sys
import json
import subprocess
import tempfile
from pathlib import Path
from datetime import datetime

REVIEW_OUTPUT_DIR = Path(__file__).parent.parent / "review-output"
REPO = "FlossWare/classloader-java"
ISSUE_LABEL = "code-quality"
ISSUE_PREFIX = "[Brutal Review]"


def run_gh_command(cmd):
    """Run a gh CLI command and return the output."""
    try:
        result = subprocess.run(
            cmd,
            shell=True,
            capture_output=True,
            text=True,
            check=True
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(f"Error running command: {cmd}", file=sys.stderr)
        print(f"Error: {e.stderr}", file=sys.stderr)
        return None


def get_existing_issues():
    """Get all existing brutal review issues."""
    cmd = f'gh issue list --repo {REPO} --label "{ISSUE_LABEL}" --json number,title,state --limit 1000'
    output = run_gh_command(cmd)
    if output:
        return json.loads(output)
    return []


def create_github_issue(issue):
    """Create a GitHub issue using a temp file for the body."""
    title = issue["title"]
    body = issue["body"]
    labels = issue.get("labels", [ISSUE_LABEL])

    # Add metadata
    body += f"\n\n---\n*Generated by brutal code review on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*"

    # Write body to temp file
    with tempfile.NamedTemporaryFile(mode='w', suffix='.md', delete=False) as f:
        f.write(body)
        body_file = f.name

    try:
        labels_str = ",".join(labels)
        cmd = f'gh issue create --repo {REPO} --title "{title}" --body-file "{body_file}" --label "{labels_str}"'

        result = run_gh_command(cmd)
        if result:
            print(f"✓ Created issue: {title}")
            return True
        else:
            print(f"✗ Failed to create issue: {title}")
            return False
    finally:
        Path(body_file).unlink(missing_ok=True)


def parse_brutal_findings():
    """Parse all brutal review outputs and create issues."""
    issues = []

    # 1. Missing JavaDoc
    javadoc_file = REVIEW_OUTPUT_DIR / "brutal-missing-javadoc.txt"
    if javadoc_file.exists():
        with open(javadoc_file) as f:
            lines = f.readlines()
        if lines:
            sample = ''.join(lines[:20])
            issues.append({
                "title": f"{ISSUE_PREFIX} {len(lines)} public APIs missing JavaDoc",
                "body": f"**Severity:** HIGH\n\nFound {len(lines)} public classes/methods without JavaDoc documentation.\n\n**Impact:** API consumers don't know how to use the code.\n\n**Sample findings:**\n```\n{sample}```\n\n**Action Required:** Add comprehensive JavaDoc to all public APIs.",
                "labels": [ISSUE_LABEL]
            })

    # 2. Magic Numbers
    magic_file = REVIEW_OUTPUT_DIR / "brutal-magic-numbers.txt"
    if magic_file.exists():
        with open(magic_file) as f:
            lines = f.readlines()
        if lines:
            sample = ''.join(lines[:15])
            issues.append({
                "title": f"{ISSUE_PREFIX} {len(lines)} magic numbers found",
                "body": f"**Severity:** MEDIUM\n\nFound {len(lines)} magic numbers (hardcoded literals) that should be named constants.\n\n**Impact:** Reduces code maintainability and clarity.\n\n**Sample findings:**\n```\n{sample}```\n\n**Action Required:** Extract to well-named constants.",
                "labels": [ISSUE_LABEL]
            })

    # 3. God Classes
    god_file = REVIEW_OUTPUT_DIR / "brutal-god-classes.txt"
    if god_file.exists():
        with open(god_file) as f:
            lines = f.readlines()
        if lines:
            issues.append({
                "title": f"{ISSUE_PREFIX} {len(lines)} God Classes detected (>500 lines)",
                "body": f"**Severity:** HIGH\n\nFound {len(lines)} classes exceeding 500 lines - violates Single Responsibility Principle.\n\n**Largest offenders:**\n```\n{''.join(lines)}```\n\n**Action Required:** Refactor into smaller, focused classes.",
                "labels": [ISSUE_LABEL]
            })

    # 4. Deep Nesting
    nest_file = REVIEW_OUTPUT_DIR / "brutal-deep-nesting.txt"
    if nest_file.exists():
        with open(nest_file) as f:
            lines = f.readlines()
        if lines:
            sample = ''.join(lines[:10])
            issues.append({
                "title": f"{ISSUE_PREFIX} {len(lines)} deeply nested statements (>3 levels)",
                "body": f"**Severity:** MEDIUM\n\nFound {len(lines)} statements with excessive nesting.\n\n**Impact:** Hard to read, test, and maintain. High cyclomatic complexity.\n\n**Sample findings:**\n```\n{sample}```\n\n**Action Required:** Extract methods, use guard clauses, reduce nesting.",
                "labels": [ISSUE_LABEL]
            })

    # 5. Missing Null Checks
    null_file = REVIEW_OUTPUT_DIR / "brutal-missing-null-checks.txt"
    if null_file.exists():
        with open(null_file) as f:
            lines = f.readlines()
        if len(lines) > 10:  # Only report if significant
            sample = ''.join(lines[:10])
            issues.append({
                "title": f"{ISSUE_PREFIX} {len(lines)} methods potentially missing null validation",
                "body": f"**Severity:** HIGH\n\nFound {len(lines)} methods accepting object parameters without null checks.\n\n**Impact:** NullPointerException risk.\n\n**Sample findings:**\n```\n{sample}```\n\n**Action Required:** Add Objects.requireNonNull() or @Nullable annotations.",
                "labels": [ISSUE_LABEL]
            })

    # 6. Mutable Static Fields
    mutable_file = REVIEW_OUTPUT_DIR / "brutal-mutable-static.txt"
    if mutable_file.exists():
        with open(mutable_file) as f:
            lines = f.readlines()
        if lines:
            issues.append({
                "title": f"{ISSUE_PREFIX} {len(lines)} mutable static fields found",
                "body": f"**Severity:** CRITICAL\n\nFound {len(lines)} mutable static fields - major thread-safety issue.\n\n**Findings:**\n```\n{''.join(lines)}```\n\n**Action Required:** Make final or use proper synchronization.",
                "labels": [ISSUE_LABEL]
            })

    # 7. Resource Leaks
    leak_file = REVIEW_OUTPUT_DIR / "brutal-resource-leaks.txt"
    if leak_file.exists():
        with open(leak_file) as f:
            lines = f.readlines()
        if lines:
            sample = ''.join(lines[:10])
            issues.append({
                "title": f"{ISSUE_PREFIX} {len(lines)} potential resource leaks",
                "body": f"**Severity:** HIGH\n\nFound {len(lines)} resource allocations not using try-with-resources.\n\n**Impact:** Memory leaks, file handle exhaustion.\n\n**Sample findings:**\n```\n{sample}```\n\n**Action Required:** Use try-with-resources for AutoCloseable resources.",
                "labels": [ISSUE_LABEL]
            })

    # 8. Broad Exception Catching
    broad_file = REVIEW_OUTPUT_DIR / "brutal-broad-exceptions.txt"
    if broad_file.exists():
        with open(broad_file) as f:
            lines = f.readlines()
        if lines:
            sample = ''.join(lines[:15])
            issues.append({
                "title": f"{ISSUE_PREFIX} {len(lines)} overly broad exception catches",
                "body": f"**Severity:** MEDIUM\n\nFound {len(lines)} catch blocks catching generic Exception/Throwable.\n\n**Impact:** Hides bugs, catches errors that shouldn't be caught.\n\n**Sample findings:**\n```\n{sample}```\n\n**Action Required:** Catch specific exception types.",
                "labels": [ISSUE_LABEL]
            })

    # 9. Missing @Override
    override_file = REVIEW_OUTPUT_DIR / "brutal-missing-override.txt"
    if override_file.exists():
        with open(override_file) as f:
            lines = f.readlines()
        if lines:
            issues.append({
                "title": f"{ISSUE_PREFIX} {len(lines)} missing @Override annotations",
                "body": f"**Severity:** LOW\n\nFound {len(lines)} override methods without @Override annotation.\n\n**Findings:**\n```\n{''.join(lines)}```\n\n**Action Required:** Add @Override annotations.",
                "labels": [ISSUE_LABEL]
            })

    return issues


def main():
    """Main function to process brutal review and create issues."""
    if not REVIEW_OUTPUT_DIR.exists():
        print(f"Review output directory not found: {REVIEW_OUTPUT_DIR}")
        return

    print("Parsing brutal review outputs...")
    issues = parse_brutal_findings()

    if not issues:
        print("No issues found in brutal review outputs.")
        return

    print(f"Found {len(issues)} issue categories")

    # Get existing issues to avoid duplicates
    existing_issues = get_existing_issues()
    existing_titles = {issue["title"] for issue in existing_issues if issue["state"] == "open"}

    # Create new issues
    created_count = 0
    for issue in issues:
        if issue["title"] in existing_titles:
            print(f"⊘ Skipping duplicate: {issue['title']}")
            continue

        if create_github_issue(issue):
            created_count += 1

    print(f"\nCreated {created_count} new issues out of {len(issues)} categories")


if __name__ == "__main__":
    main()
